### PR TITLE
Add dummy.txt

### PR DESCRIPTION
**Pull request by rwy7**
Closes: #1
Signed-off-by: Robert Young <rwy0717@gmail.com>

### CODE REVIEW

**Comment by keithc-ca** [comment]
Perhaps my problem was that I wrote `Fixes issue #726` instead of just `Fixes #726`?
See https://github.com/eclipse/omr/pull/727.
Maybe the colon doesn't interfere.
The question is: If you merge this, does the issue get closed automatically? If so, I'll retract https://github.com/eclipse/omr/pull/1509.

**Comment by rwy7** [comment]
Accepting this PR closed #1 successfully.

**Comment by keithc-ca** [comment]
Thanks for your help.

**Comment by rwy7** [comment]
NP! I still think you've started an interesting discussion, on relaxing the commit standard to work better with the github Closes/Fixes syntax.

**Pull request merged**
